title: Alex Hammerschmied's Blog
description: This is my blog written with AI about how to work with AI and use it to build amazing things!
author:
  name: Alex Hammerschmied
baseurl: ""
url: "https://alexhammerschmied.github.io"

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Permalink structure
permalink: /:title/
